hot water zone compatibility bug fix
erwindouna/python-tado pull request #81
Opened 2024-09-01 20:29 UTC by ethemcemozkan

# Proposed Changes
Please see my comments in the HA PR https://github.com/home-assistant/core/pull/121503#issuecomment-2323477115

Due to missing hot water zone attributes(dazzleMode enabled  and open_window_detection enabled  timeout_in_seconds), integration setup flow was failing. I made these local changes to fix the issue. Feel free to let me know if you have a better idea.

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

2024-10-02 12:54 UTC, ethemcemozkan commented
Still related

2024-10-19 11:20 UTC, erwindouna requested changes
Thanks for addressing this! I don't think the _Optional_ is needed, where as a default value is always assigned. Unless I am overlooking something? :)

2024-10-19 11:20 UTC, erwindouna commented on src/tadoasync/models.py
> +    enabled: Optional[bool] = field(default=False)
```suggestion
    enabled: bool = field(default=False)
```

2024-10-19 11:20 UTC, erwindouna commented on src/tadoasync/models.py
> +    enabled: Optional[bool] = field(default=False)
```suggestion
    enabled: bool = field(default=False)
```

2024-10-19 11:20 UTC, erwindouna commented on src/tadoasync/models.py
> +    timeout_in_seconds: Optional[int] = field(metadata=field_options(alias="timeoutInSeconds"), default=0)
```suggestion
    timeout_in_seconds: int = field(metadata=field_options(alias="timeoutInSeconds"), default=0)
```

2024-10-20 10:33 UTC, erwindouna approved these changes
Thanks @ethemcemozkan!

2024-10-20 10:33 UTC, merged